name: locale_gen
description: Dart tool that will convert your default locale json to dart code.
version: 0.1.0
author: Koen Van Looveren <vanlooverenkoen.dev@gmail.com>
homepage: https://github.com/vanlooverenkoen/locale_gen

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  path: ^1.6.2
  yaml: ^2.1.15

dev_dependencies:
  test: ^1.0.0
