name: locale_gen
description: Dart tool that will convert your default locale json to dart code.
version: 2.0.3
homepage: https://github.com/vanlooverenkoen/locale_gen

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  path: ^1.6.2
  yaml: ^2.1.15
  meta: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dartfmt
  test: ^1.0.0
